In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/majdshamashan/Downloads/data.csv')

/var/folders/h0/cmm4fsss18l_d3l4lkzj5pxc0000gn/T/ipykernel_33533/116339913.py:1: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/majdshamashan/Downloads/data.csv')

In [3]:
df

,ID,Country,VFN,Mp,Mh,Man,MMS,Tan,T,Va,...,Erwltp (g/km),De,Vf,Status,year,Date of registration,Fuel consumption,ech,RLFI,Electric range (km)
0,176934618,DE,IP-0001199-WBA,BMW,BMW AG,BAYERISCHE MOTOREN WERKE AG,NaN,E1*2018/858*00370*04,UMX,11GA,...,NaN,NaN,NaN,P,2025,2025-09-23,5.9,EC,RL-0101042-WBA,NaN
1,176934616,DE,IP-MQB37WZ_B1_1270-WAU,NaN,AUDI AG,AUDI AG,NaN,E1*2007/46*2060*39,GY,SDUCAF1,...,NaN,NaN,NaN,P,2025,2025-10-24,0.4,EA,RL-DQ400E6F_19_001-WAU,127.0
2,176934615,DE,IP-2023_4043-W1K,"MERCEDES-BENZ, VOLVO CARS, POLESTAR AND SMART",MERCEDES-BENZ AG,MERCEDES-BENZ AG,NaN,E1*2007/46*1830*16,463A,CNEZZ1,...,NaN,NaN,NaN,P,2025,2025-09-09,NaN,E,RL-2023_0040-W1K,415.0
3,176934614,DE,IP-2022_8401-W1K,"MERCEDES-BENZ, VOLVO CARS, POLESTAR AND SMART",MERCEDES-BENZ AG,MERCEDES-BENZ AG,NaN,E1*2018/858*00186*14,R2CGLC,8604T1,...,2.01,NaN,NaN,P,2025,2025-08-08,5.3,EB,RL-2021_0145-W1K,NaN
4,176934613,DE,IP-MEB31AZ_A1_1992-TMB,NaN,SKODA,SKODA AUTO AS,NaN,E8*2007/46*0416*18,NY,ABLEDFAD7PX2,...,NaN,NaN,NaN,P,2025,2025-07-01,NaN,AX,RL-EQ550_1P_23_008-TMB,570.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5652491,184515649,PL,IP-2023_8414-W1K,"MERCEDES-BENZ, VOLVO CARS, POLESTAR AND SMART",MERCEDES-BENZ AG,MERCEDES-BENZ AG,NaN,E1*2018/858*00186*14,R2CGLC,861NT1,...,2.00,NaN,NaN,P,2025,2025-11-06,5.8,EURO 6 EA,RM-1-W1N,NaN
5652492,184515648,PL,IP-MQB37WZ_A1_1236-TMB,NaN,SKODA,SKODA AUTO AS,NaN,E8*2007/46*0355*23,NX,ACDXDBX0,...,NaN,NaN,NaN,P,2025,2025-07-01,5.8,EURO 6 EA,RM-1-TMB,NaN
5652493,184515647,PL,IP-0211-JT1,TESLA,TOYOTA MOTOR CORPORATION,TOYOTA MOTOR CORPORATION,NaN,E6*2018/858*00294*02,AX2T(M),ZYX20(H),...,NaN,NaN,NaN,P,2025,2025-06-12,5.8,EURO 6 EA,RM-1-JTP,NaN
5652494,184515646,PL,IP-MQB37WZ_A0_1281-WVW,NaN,VOLKSWAGEN,VOLKSWAGEN AG,NaN,E1*2007/46*2014*31,CD,ACDNFCX0,...,NaN,NaN,NaN,P,2025,2025-10-24,5.8,EURO 6 EA,RM-1-WVW,NaN
5652495,184515644,PL,IP-0153-JT1-1,TESLA,TOYOTA MOTOR CORPORATION,TOYOTA MOTOR CORPORATION,NaN,E6*2018/858*00013*05,XPB1F(M),MXPJ10(H),...,NaN,NaN,NaN,P,2025,2025-09-09,5.8,EURO 6 EA,RM-1-JTD,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5652496 entries, 0 to 5652495
Data columns (total 37 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Country               object
 2   VFN                   object
 3   Mp                    object
 4   Mh                    object
 5   Man                   object
 6   MMS                   float64
 7   Tan                   object
 8   T                     object
 9   Va                    object
 10  Ve                    object
 11  Mk                    object
 12  Cn                    object
 13  Ct                    object
 14  Cr                    object
 15  r                     int64
 16  m (kg)                int64
 17  Mt                    float64
 18  Enedc (g/km)          float64
 19  Ewltp (g/km)          float64
 20  Ft                    object
 21  Fm                    object
 22  ec (cm3)              float64
 23  ep (KW)               float64
 24  z (Wh/km)             float64
 25  IT                    object
 26  Ernedc (g/km)         float64
 27  Erwltp (g/km)         float64
 28  De                    float64
 29  Vf                    float64
 30  Status                object
 31  year                  int64
 32  Date of registration  object
 33  Fuel consumption      float64
 34  ech                   object
 35  RLFI                  object
 36  Electric range (km)   float64
dtypes: float64(13), int64(4), object(20)
memory usage: 1.6+ GB

In [10]:
mask = df[['Mk', 'Cn', 'year', 'm (kg)', 'r', 'Ct', 'Ft', 'Ewltp (g/km)', 'Country' ]]

In [11]:
mask

,Mk,Cn,year,m (kg),r,Ct,Ft,Ewltp (g/km),Country
0,MINI,COUNTRYMAN COOPER,2025,1620,1,M1,petrol,134.0,DE
1,AUDI,A3 SPORTBACK PHEV 200,2025,1685,1,M1,petrol/electric,8.0,DE
2,MERCEDES-BENZ,G 580,2025,3085,1,M1,electric,0.0,DE
3,MERCEDES-BENZ,GLC 220 D 4MATIC,2025,1985,1,M1,diesel,138.0,DE
4,SKODA,ELROQ 85,2025,2119,1,M1,electric,0.0,DE
...,...,...,...,...,...,...,...,...,...
5652491,MERCEDES-BENZ,GLC 200 D 4MATIC,2025,1921,1,M1,diesel,129.0,PL
5652492,SKODA,OCTAVIA,2025,1341,1,M1,petrol,124.0,PL
5652493,TOYOTA,TOYOTA C-HR,2025,1443,1,M1,petrol,102.0,PL
5652494,VOLKSWAGEN,GOLF,2025,1430,1,M1,petrol,168.0,PL
5652495,TOYOTA,YARIS CROSS,2025,1201,1,M1,petrol,111.0,PL

In [14]:
mask.to_csv('/Users/majdshamashan/Downloads/mask_eea_data.csv')

In [13]:
mask.drop_duplicates()

,Mk,Cn,year,m (kg),r,Ct,Ft,Ewltp (g/km),Country
0,MINI,COUNTRYMAN COOPER,2025,1620,1,M1,petrol,134.0,DE
1,AUDI,A3 SPORTBACK PHEV 200,2025,1685,1,M1,petrol/electric,8.0,DE
2,MERCEDES-BENZ,G 580,2025,3085,1,M1,electric,0.0,DE
3,MERCEDES-BENZ,GLC 220 D 4MATIC,2025,1985,1,M1,diesel,138.0,DE
4,SKODA,ELROQ 85,2025,2119,1,M1,electric,0.0,DE
...,...,...,...,...,...,...,...,...,...
5652449,MERCEDES-BENZ,GLS 450 D 4MATIC,2025,2646,1,M1G,diesel,226.0,PL
5652455,SKODA,KAMIQ,2025,1262,1,M1,petrol,129.0,PL
5652461,SKODA,OCTAVIA RS,2025,1566,1,M1,petrol,163.0,PL
5652464,VOLKSWAGEN,CADDY,2025,1687,1,M1,diesel,158.0,PL
5652469,AUDI,S5 LIMOUSINE,2025,2053,1,M1,petrol,177.0,PL